package com.gei.autoant.cli;

import com.gei.autoant.deploy.DeploymentLock;
import com.gei.autoant.deploy.DeploymentState;
import com.gei.autoant.deploy.ReconcileConfiguration;
import com.gei.autoant.deploy.SnapshotPromoter;
import com.gei.autoant.generate.InitGenerator;
import com.gei.autoant.run.AntRunner;
import com.gei.autoant.run.CommandResult;
import com.gei.autoant.tomcat.TomcatManagerClient;
import com.gei.autoant.tomcat.TomcatManagerResponse;
import com.gei.autoant.util.PathUtils;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

public final class ReconcileCommand {
    private final CommandContext context;
    private final AntTargetRunner antRunner;
    private final TomcatManagerClient manager;
    private final SnapshotPromoter promoter;

    public ReconcileCommand(CommandContext context) {
        this(context, (root, build, target, properties) -> new AntRunner(context.out(), context.err()).runTarget(root, build, target, properties),
                new TomcatManagerClient(), new SnapshotPromoter());
    }

    ReconcileCommand(CommandContext context, AntTargetRunner antRunner, TomcatManagerClient manager, SnapshotPromoter promoter) {
        this.context = context;
        this.antRunner = antRunner;
        this.manager = manager;
        this.promoter = promoter;
    }

    public int run(String[] args) {
        CommandLine line = CommandLine.parse(args);
        if (line.hasAnyOption("help", "h")) {
            printHelp();
            return 0;
        }
        Path root = line.option("root").map(value -> PathUtils.resolve(context.projectRoot(), value))
                .orElse(context.projectRoot()).toAbsolutePath().normalize();
        if (line.hasOption("install-hook")) {
            try {
                return new GitHookInstaller(context).install(root);
            } catch (IOException | IllegalArgumentException ex) {
                context.err().println("reconcile: " + ex.getMessage());
                return 1;
            }
        }
        long waitMillis;
        try {
            waitMillis = line.option("lock-wait-seconds").map(Long::parseLong).orElse(30L) * 1000L;
            if (waitMillis < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            context.err().println("reconcile: --lock-wait-seconds must be a non-negative integer.");
            return 2;
        }

        try {
            ReconcileConfiguration configuration = ReconcileConfiguration.load(root);
            DeploymentState state = new DeploymentState(configuration);
            try (DeploymentLock ignored = DeploymentLock.acquire(configuration, waitMillis)) {
                SnapshotPromoter.RecoveryResult recovery = promoter.recover(configuration.deployDirectory());
                if (!recovery.safeToProceed()) {
                    state.markCritical("Pending promotion recovery requires manual intervention: " + recovery.message());
                    context.err().println("reconcile: " + recovery.message());
                    context.err().println("Tomcat must remain stopped. Do not delete the reported live/stage/backup/journal artifacts until recovery is complete.");
                    return 1;
                }
                if (recovery.state() == SnapshotPromoter.TransactionState.ROLLED_BACK) {
                    context.out().println("reconcile: " + recovery.message());
                }
                return reconcile(configuration, state, line.hasOption("confirm-stopped"), line.hasOption("force"));
            }
        } catch (IllegalArgumentException ex) {
            context.err().println("reconcile: " + ex.getMessage());
            context.err().println("Run auto-ant update if this project was generated by an older auto-ant version.");
            return 2;
        } catch (DeploymentLock.LockUnavailableException ex) {
            context.err().println("reconcile: " + ex.getMessage());
            return 3;
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            context.err().println("reconcile: interrupted");
            return 130;
        } catch (IOException ex) {
            context.err().println("reconcile: " + ex.getMessage());
            return 1;
        } catch (RuntimeException ex) {
            context.err().println("reconcile: " + ex.getMessage());
            return 1;
        }
    }

    private int reconcile(ReconcileConfiguration configuration, DeploymentState state,
                          boolean confirmStopped, boolean force) throws IOException, InterruptedException {
        String fingerprint = state.fingerprint(configuration);
        if (!force && state.isCurrent(fingerprint, configuration.deployDirectory()) && !state.isStale()) {
            context.out().println("Deployment is already current; no reconcile was needed.");
            return 0;
        }

        Lifecycle lifecycle = establishLifecycle(configuration, confirmStopped);
        if (lifecycle == null) {
            state.markStale("Reconcile refused because Tomcat running state could not be made safe.");
            return 1;
        }

        Path buildFile = configuration.projectRoot().resolve(InitGenerator.AUTO_ANT_BUILD_FILE);
        if (Files.notExists(buildFile)) {
            state.markStale("Generated build file is missing.");
            context.err().println("reconcile: " + InitGenerator.AUTO_ANT_BUILD_FILE + " not found. Run auto-ant update.");
            return 1;
        }

        Path snapshot;
        try {
            snapshot = controlledSnapshotPath(configuration);
        } catch (IOException ex) {
            state.markStale("Controlled snapshot path could not be created: " + ex.getMessage());
            context.err().println("reconcile: " + redact(ex.getMessage()));
            return 1;
        }
        context.out().println("Building full deployment snapshot into controlled output...");
        CommandResult build = antRunner.run(configuration.projectRoot(), buildFile, "reconcile-snapshot", Map.of(
                "reconcile.output.dir", snapshot.toString(),
                "build.dir", snapshot.toString(),
                "build.web.dir", snapshot.toString(),
                "classes.dir", snapshot.resolve("WEB-INF/classes").toString(),
                "dist.dir", snapshot.resolve(".dist-disabled").toString()));
        if (build.exitCode() != 0) {
            try {
                promoter.discardBuildOutput(snapshot, configuration.deployDirectory());
            } catch (IOException cleanup) {
                state.markCritical("Failed snapshot build cleanup; controlled artifact preserved at " + snapshot + ": " + cleanup.getMessage());
                context.err().println("reconcile: snapshot build failed and controlled output cleanup also failed; artifact preserved at " + snapshot + ".");
                return build.exitCode() == 0 ? 1 : build.exitCode();
            }
            state.markStale("Snapshot build failed with exit code " + build.exitCode() + ".");
            context.err().println("reconcile: snapshot build failed; live deployment was not changed.");
            return build.exitCode();
        }

        SnapshotPromoter.PreparedSnapshot prepared;
        try {
            prepared = promoter.stage(snapshot, configuration.deployDirectory());
            promoter.discardBuildOutput(snapshot, configuration.deployDirectory());
        } catch (IOException ex) {
            state.markStale("Snapshot staging failed: " + ex.getMessage());
            context.err().println("reconcile: snapshot staging failed; live deployment was not changed: " + redact(ex.getMessage()));
            return 1;
        }
        SnapshotPromoter.PromotionResult promotion = null;
        boolean stopped = false;
        try {
            if (lifecycle == Lifecycle.MANAGER_RUNNING) {
                stopAndConfirm(configuration, "stop");
                stopped = true;
            }
            promotion = promoter.promote(prepared);
            if (lifecycle == Lifecycle.MANAGER_RUNNING) {
                requireSuccessful(manager.start(configuration.managerUrl(), configuration.contextPath(), configuration.managerUser(), configuration.managerPassword()), "start");
                stopped = false;
                if (!manager.waitUntilRunning(configuration.managerUrl(), configuration.contextPath(), configuration.managerUser(), configuration.managerPassword(),
                        configuration.readinessTimeoutSeconds(), configuration.readinessPollMillis())) {
                    throw new IOException("Tomcat context did not become ready before the configured timeout.");
                }
            }
            state.markSuccess(fingerprint, configuration);
            try {
                promoter.complete(promotion);
            } catch (IOException cleanupFailure) {
                context.err().println("reconcile: deployment succeeded, but the backup could not be removed: " + redact(cleanupFailure.getMessage()));
            }
            context.out().println("Reconciled full snapshot to " + PathUtils.toPortableString(configuration.deployDirectory()) + ".");
            return 0;
        } catch (IOException | InterruptedException ex) {
            if (ex instanceof SnapshotPromoter.PromotionException promotionFailure
                    && !promotionFailure.rollback().complete()) {
                state.markCritical("Promotion rollback incomplete or uncertain: " + promotionFailure.getMessage());
                context.err().println("reconcile: CRITICAL promotion rollback is uncertain; Tomcat will NOT be restarted.");
                context.err().println("Preserve live=" + promotionFailure.prepared().live() + ", backup=" + promotionFailure.prepared().backup()
                        + ", stage=" + promotionFailure.prepared().stage() + ", journal=" + promotionFailure.prepared().journal() + ".");
                return failureExit(ex);
            }
            if (lifecycle == Lifecycle.MANAGER_RUNNING && promotion != null) {
                try {
                    TomcatManagerClient.ContextState current = manager.contextState(
                            manager.list(configuration.managerUrl(), configuration.managerUser(), configuration.managerPassword()), configuration.contextPath());
                    if (current == TomcatManagerClient.ContextState.RUNNING) stopAndConfirm(configuration, "rollback stop");
                    else if (current != TomcatManagerClient.ContextState.STOPPED) throw new IOException("Exact target state before rollback is " + current + ".");
                    stopped = true;
                } catch (IOException stopFailure) {
                    ex.addSuppressed(stopFailure);
                    state.markStale("Rollback was refused because the promoted context could not be stopped: " + stopFailure.getMessage());
                    context.err().println("reconcile: promoted context could not be stopped for rollback; backup was preserved: " + redact(stopFailure.getMessage()));
                    return failureExit(ex);
                }
            }
            if (promotion != null) {
                SnapshotPromoter.RollbackResult rollback = promoter.rollback(promotion);
                if (!rollback.complete()) {
                    if (rollback.failure() != null) ex.addSuppressed(rollback.failure());
                    state.markCritical("Rollback incomplete or uncertain: " + (rollback.failure() == null ? rollback.state() : rollback.failure().getMessage()));
                    context.err().println("reconcile: CRITICAL rollback is incomplete or uncertain; Tomcat will NOT be restarted.");
                    context.err().println("Preserve live=" + promotion.live() + ", backup=" + promotion.backup() + ", stage=" + promotion.stage() + ", journal=" + promotion.journal() + ".");
                    context.err().println("Manually inspect these artifacts while the target context remains stopped, restore exactly one known-good live directory, then rerun reconcile.");
                    return failureExit(ex);
                }
            } else if (!(ex instanceof SnapshotPromoter.PromotionException)) {
                try {
                    promoter.discard(prepared);
                } catch (IOException cleanupFailure) {
                    ex.addSuppressed(cleanupFailure);
                    state.markCritical("Snapshot cleanup failed; artifacts preserved: " + cleanupFailure.getMessage());
                    context.err().println("reconcile: staged snapshot cleanup failed; Tomcat will NOT be restarted: " + redact(cleanupFailure.getMessage()));
                    return failureExit(ex);
                }
            }
            if (lifecycle == Lifecycle.MANAGER_RUNNING && stopped) {
                try {
                    requireSuccessful(manager.start(configuration.managerUrl(), configuration.contextPath(), configuration.managerUser(), configuration.managerPassword()), "rollback restart");
                    if (!manager.waitUntilRunning(configuration.managerUrl(), configuration.contextPath(), configuration.managerUser(), configuration.managerPassword(),
                            configuration.readinessTimeoutSeconds(), configuration.readinessPollMillis())) {
                        throw new IOException("Tomcat rollback restart did not become ready before the configured timeout.");
                    }
                } catch (IOException | InterruptedException startFailure) {
                    ex.addSuppressed(startFailure);
                    state.markStale("Previous deployment was restored, but rollback restart/readiness failed: " + startFailure.getMessage());
                    context.err().println("reconcile: previous deployment was restored, but rollback restart/readiness failed: " + redact(startFailure.getMessage()));
                    return failureExit(startFailure);
                }
            }
            state.markStale("Reconcile failed during lifecycle/promotion: " + ex.getMessage());
            context.err().println("reconcile: promotion failed; prior live deployment was restored or preserved: " + redact(ex.getMessage()));
            return failureExit(ex);
        }
    }

    private int failureExit(Exception failure) throws InterruptedException {
        if (failure instanceof InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            throw interrupted;
        }
        return 1;
    }

    private Lifecycle establishLifecycle(ReconcileConfiguration configuration, boolean confirmStopped) throws IOException {
        if (configuration.managerLifecycleConfigured()) {
            TomcatManagerResponse list = manager.list(configuration.managerUrl(), configuration.managerUser(), configuration.managerPassword());
            if (!list.successful()) {
                context.err().println("reconcile: Tomcat Manager state check failed with HTTP " + list.statusCode() + "; refusing live mutation.");
                return null;
            }
            TomcatManagerClient.ContextState state = manager.contextState(list, configuration.contextPath());
            return switch (state) {
                case RUNNING -> Lifecycle.MANAGER_RUNNING;
                case STOPPED -> Lifecycle.MANAGER_STOPPED;
                case MISSING, UNKNOWN_ERROR -> {
                    context.err().println("reconcile: exact target context state is " + state + "; refusing live mutation.");
                    yield null;
                }
            };
        }
        if (!confirmStopped) {
            context.err().println("reconcile: automatic lifecycle is unavailable. Stop Tomcat, then rerun with --confirm-stopped.");
            context.err().println("Live mutation is refused when server state cannot be established safely.");
            return null;
        }
        context.out().println("Proceeding on explicit confirmation that Tomcat is stopped.");
        return Lifecycle.CONFIRMED_STOPPED;
    }

    private void requireSuccessful(TomcatManagerResponse response, String action) throws IOException {
        if (!response.successful()) {
            String firstLine = response.body() == null ? "" : response.body().lines().findFirst().orElse("").trim();
            throw new IOException("Tomcat Manager " + action + " failed with HTTP " + response.statusCode()
                    + (firstLine.isBlank() ? " and no valid OK response." : " and response '" + redact(firstLine) + "'."));
        }
    }

    private Path controlledSnapshotPath(ReconcileConfiguration configuration) throws IOException {
        return promoter.createBuildOutput(configuration.deployDirectory());
    }

    private void stopAndConfirm(ReconcileConfiguration configuration, String action) throws IOException {
        requireSuccessful(manager.stop(configuration.managerUrl(), configuration.contextPath(), configuration.managerUser(), configuration.managerPassword()), action);
        TomcatManagerClient.ContextState stoppedState = manager.contextState(
                manager.list(configuration.managerUrl(), configuration.managerUser(), configuration.managerPassword()), configuration.contextPath());
        if (stoppedState != TomcatManagerClient.ContextState.STOPPED) {
            throw new IOException("Tomcat Manager did not confirm the exact target context as stopped (state=" + stoppedState + ").");
        }
    }

    private String redact(String value) {
        if (value == null || value.isBlank()) {
            return "unknown failure";
        }
        return value.replaceAll("(?i)(password|authorization|credential)[^,; ]*", "$1=<redacted>");
    }

    private void printHelp() {
        context.out().println("Usage: auto-ant reconcile [options]");
        context.out().println();
        context.out().println("Builds a full staged snapshot and safely promotes it under a cross-process deployment lock.");
        context.out().println("branch-refresh is a compatibility alias for this command.");
        context.out().println();
        context.out().println("Options:");
        context.out().println("  --root <path>              Project root. Defaults to current directory.");
        context.out().println("  --install-hook             Install composed Git reconciliation hooks.");
        context.out().println("  --confirm-stopped          Explicitly confirm Tomcat is stopped when Manager lifecycle is unavailable.");
        context.out().println("  --lock-wait-seconds <n>    Bounded lock wait; 0 is fail-fast (default 30).");
        context.out().println("  --force                    Rebuild even when the fingerprint is already current.");
    }

    private enum Lifecycle { MANAGER_RUNNING, MANAGER_STOPPED, CONFIRMED_STOPPED }

    @FunctionalInterface
    interface AntTargetRunner {
        CommandResult run(Path root, Path buildFile, String target, Map<String, String> userProperties) throws IOException, InterruptedException;
    }
}
