package com.gei.autoant.generate;

import com.gei.autoant.model.ProjectModel;
import com.gei.autoant.util.PathUtils;

import java.nio.file.Path;
import java.util.List;

public final class BuildXmlWriter {
    public String write(ProjectModel model) {
        StringBuilder sourcePath = new StringBuilder();
        for (Path sourceRoot : ModelValues.sourceRoots(model)) {
            sourcePath.append("        <pathelement location=\"")
                    .append(escape(ModelValues.relativePath(model, sourceRoot)))
                    .append("\"/>\n");
        }

        StringBuilder classpath = new StringBuilder();
        for (Path libraryRoot : ModelValues.libraryRoots(model)) {
            classpath.append("        <fileset dir=\"")
                    .append(escape(ModelValues.relativePath(model, libraryRoot)))
                    .append("\" erroronmissingdir=\"false\">\n")
                    .append("            <include name=\"**/*.jar\"/>\n")
                    .append("        </fileset>\n");
        }

        StringBuilder copyLibs = new StringBuilder();
        for (Path libraryRoot : ModelValues.libraryRoots(model)) {
            copyLibs.append("        <copy todir=\"${build.web.dir}/WEB-INF/lib\" failonerror=\"false\">\n")
                    .append("            <fileset dir=\"")
                    .append(escape(ModelValues.relativePath(model, libraryRoot)))
                    .append("\" erroronmissingdir=\"false\">\n")
                    .append("                <include name=\"**/*.jar\"/>\n")
                    .append("            </fileset>\n")
                    .append("        </copy>\n");
        }

        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<project name=\"" + escape(ModelValues.appName(model)) + "\" default=\"clean-build\" basedir=\".\">\n"
                + "    <description>Plain Ant build generated by auto-ant for a legacy Tomcat web app.</description>\n"
                + "\n"
                + "    <property file=\"auto-ant.local.properties\"/>\n"
                + "    <property file=\"auto-ant.properties\"/>\n"
                + "\n"
                + "    <path id=\"source.path\">\n"
                + sourcePath
                + "    </path>\n"
                + "\n"
                + "    <path id=\"compile.classpath\">\n"
                + classpath
                + "    </path>\n"
                + "\n"
                + "    <target name=\"clean\" description=\"Delete build and dist output.\">\n"
                + "        <delete dir=\"${build.dir}\"/>\n"
                + "        <delete dir=\"${dist.dir}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"init\" description=\"Create build directories.\">\n"
                + "        <mkdir dir=\"${classes.dir}\"/>\n"
                + "        <mkdir dir=\"${build.web.dir}/WEB-INF/lib\"/>\n"
                + "        <mkdir dir=\"${dist.dir}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"compile\" depends=\"init\" description=\"Compile Java source into WEB-INF/classes.\">\n"
                + "        <javac destdir=\"${classes.dir}\" includeantruntime=\"false\" debug=\"true\" release=\"${java.release}\">\n"
                + "            <src refid=\"source.path\"/>\n"
                + "            <classpath refid=\"compile.classpath\"/>\n"
                + "        </javac>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"copy-web\" depends=\"init\" description=\"Copy web root into the exploded build directory.\">\n"
                + "        <copy todir=\"${build.web.dir}\">\n"
                + "            <fileset dir=\"${web.dir}\" erroronmissingdir=\"false\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"copy-libs\" depends=\"init\" description=\"Copy project libraries into WEB-INF/lib.\">\n"
                + copyLibs
                + "    </target>\n"
                + "\n"
                + "    <target name=\"war\" depends=\"copy-web,compile,copy-libs\" description=\"Create dist WAR.\">\n"
                + "        <war destfile=\"${dist.dir}/${war.name}\" basedir=\"${build.web.dir}\" needxmlfile=\"false\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"clean-build\" depends=\"clean,war\" description=\"Clean and build WAR.\"/>\n"
                + "\n"
                + "    <target name=\"deploy-exploded\" depends=\"copy-web,compile,copy-libs\" description=\"Copy exploded app to Tomcat webapps.\">\n"
                + "        <fail unless=\"catalina.base\" message=\"Set catalina.base in auto-ant.local.properties.\"/>\n"
                + "        <delete dir=\"${catalina.base}/webapps/${app.name}\"/>\n"
                + "        <mkdir dir=\"${catalina.base}/webapps/${app.name}\"/>\n"
                + "        <copy todir=\"${catalina.base}/webapps/${app.name}\">\n"
                + "            <fileset dir=\"${build.web.dir}\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"deploy-war\" depends=\"war\" description=\"Copy WAR to Tomcat webapps.\">\n"
                + "        <fail unless=\"catalina.base\" message=\"Set catalina.base in auto-ant.local.properties.\"/>\n"
                + "        <copy file=\"${dist.dir}/${war.name}\" todir=\"${catalina.base}/webapps\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"sync-web\" description=\"Copy web/front-end files to deployed exploded app.\">\n"
                + "        <fail unless=\"catalina.base\" message=\"Set catalina.base in auto-ant.local.properties.\"/>\n"
                + "        <copy todir=\"${catalina.base}/webapps/${app.name}\">\n"
                + "            <fileset dir=\"${web.dir}\" erroronmissingdir=\"false\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"compile-hot\" depends=\"compile\" description=\"Compile Java and copy classes to deployed exploded app.\">\n"
                + "        <fail unless=\"catalina.base\" message=\"Set catalina.base in auto-ant.local.properties.\"/>\n"
                + "        <mkdir dir=\"${catalina.base}/webapps/${app.name}/WEB-INF/classes\"/>\n"
                + "        <copy todir=\"${catalina.base}/webapps/${app.name}/WEB-INF/classes\">\n"
                + "            <fileset dir=\"${classes.dir}\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"reload-hint\" description=\"Print Tomcat reload instructions.\">\n"
                + "        <echo message=\"Reload ${context.path} using auto-ant reload, Tomcat Manager, or restart Tomcat.\"/>\n"
                + "    </target>\n"
                + "</project>\n";
    }

    private String escape(String value) {
        return value.replace("&", "&amp;")
                .replace("\"", "&quot;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }
}