package com.gei.autoant.generate;

import com.gei.autoant.model.ProjectModel;

import java.nio.file.Path;

public final class BuildXmlWriter {
    public String write(ProjectModel model) {
        StringBuilder sourcePath = new StringBuilder();
        for (Path sourceRoot : ModelValues.sourceRoots(model)) {
            sourcePath.append("        <pathelement location=\"")
                    .append(escape(ModelValues.relativePath(model, sourceRoot)))
                    .append("\"/>\n");
        }

        StringBuilder classpath = new StringBuilder();
        for (Path libraryRoot : ModelValues.libraryRoots(model)) {
            classpath.append("        <fileset dir=\"")
                    .append(escape(ModelValues.relativePath(model, libraryRoot)))
                    .append("\" erroronmissingdir=\"false\">\n")
                    .append("            <include name=\"**/*.jar\"/>\n")
                    .append("        </fileset>\n");
        }

        StringBuilder copyLibs = new StringBuilder();
        for (Path libraryRoot : ModelValues.libraryRoots(model)) {
            copyLibs.append("        <copy todir=\"${build.web.dir}/WEB-INF/lib\" failonerror=\"false\">\n")
                    .append("            <fileset dir=\"")
                    .append(escape(ModelValues.relativePath(model, libraryRoot)))
                    .append("\" erroronmissingdir=\"false\">\n")
                    .append("                <include name=\"**/*.jar\"/>\n")
                    .append("            </fileset>\n")
                    .append("        </copy>\n");
        }

        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<!--\n"
                + "  AUTO-ANT GENERATED FILE - DO NOT EDIT DIRECTLY.\n"
                + "\n"
                + "  This file may be regenerated by auto-ant init or auto-ant update.\n"
                + "  Put project-specific custom Ant targets/properties in auto-ant.user.xml instead.\n"
                + "-->\n"
                + "<project name=\"" + escape(ModelValues.appName(model)) + "\" default=\"clean-build\" basedir=\".\">\n"
                + "    <description>Plain Ant build generated by auto-ant for a legacy Tomcat web app.</description>\n"
                + "\n"
                + "    <import file=\"auto-ant.user.xml\" optional=\"true\"/>\n"
                + "\n"
                + "    <property file=\"auto-ant.local.properties\"/>\n"
                + "    <property file=\"auto-ant.properties\"/>\n"
                + "    <property name=\"deploy.dir\" location=\"${catalina.base}/webapps/${context.deploy.name}\"/>\n"
                + "    <property name=\"context.descriptor.dir\" location=\"${catalina.base}/conf/Catalina/localhost\"/>\n"
                + "    <property name=\"context.descriptor.file\" location=\"${context.descriptor.dir}/${context.descriptor.file.name}\"/>\n"
                + "\n"
                + "    <path id=\"source.path\">\n"
                + sourcePath
                + "    </path>\n"
                + "\n"
                + "    <path id=\"compile.classpath\">\n"
                + classpath
                + "        <!-- Provided by Tomcat at runtime; needed only to compile servlet/JSP API references. -->\n"
                + "        <fileset dir=\"${tomcat.home}/lib\" erroronmissingdir=\"false\">\n"
                + "            <include name=\"*.jar\"/>\n"
                + "        </fileset>\n"
                + "        <fileset dir=\"${catalina.base}/lib\" erroronmissingdir=\"false\">\n"
                + "            <include name=\"*.jar\"/>\n"
                + "        </fileset>\n"
                + "    </path>\n"
                + "\n"
                + "    <target name=\"clean\" description=\"Delete build and dist output.\">\n"
                + "        <delete dir=\"${build.dir}\"/>\n"
                + "        <delete dir=\"${dist.dir}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"init\" description=\"Create build directories.\">\n"
                + "        <mkdir dir=\"${classes.dir}\"/>\n"
                + "        <mkdir dir=\"${build.web.dir}/WEB-INF/lib\"/>\n"
                + "        <mkdir dir=\"${dist.dir}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"compile\" depends=\"init\" description=\"Compile Java source into WEB-INF/classes.\">\n"
                + "        <delete dir=\"${classes.dir}\"/>\n"
                + "        <mkdir dir=\"${classes.dir}\"/>\n"
                + "        <javac destdir=\"${classes.dir}\" includeantruntime=\"false\" debug=\"true\" release=\"${java.release}\">\n"
                + "            <src refid=\"source.path\"/>\n"
                + "            <classpath refid=\"compile.classpath\"/>\n"
                + "        </javac>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"copy-web\" depends=\"init\" description=\"Copy web root into the exploded build directory.\">\n"
                + "        <copy todir=\"${build.web.dir}\">\n"
                + "            <fileset dir=\"${web.dir}\" erroronmissingdir=\"false\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"copy-libs\" depends=\"init\" description=\"Copy project libraries into WEB-INF/lib.\">\n"
                + copyLibs
                + "    </target>\n"
                + "\n"
                + "    <target name=\"war\" depends=\"copy-web,compile,copy-libs\" description=\"Create dist WAR.\">\n"
                + "        <war destfile=\"${dist.dir}/${war.name}\" basedir=\"${build.web.dir}\" needxmlfile=\"false\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"clean-build\" depends=\"clean,war\" description=\"Clean and build WAR.\"/>\n"
                + "\n"
                + "    <target name=\"reconcile-snapshot\" depends=\"copy-web,compile,copy-libs\" description=\"Build only into the command-line controlled snapshot consumed by auto-ant reconcile.\">\n"
                + "        <fail unless=\"reconcile.output.dir\" message=\"reconcile.output.dir must be supplied by auto-ant reconcile.\"/>\n"
                + "        <condition property=\"snapshot.output.matches\"><equals arg1=\"${build.web.dir}\" arg2=\"${reconcile.output.dir}\"/></condition>\n"
                + "        <fail unless=\"snapshot.output.matches\" message=\"Refusing snapshot build because build.web.dir is not the controlled reconcile output.\"/>\n"
                + "        <available file=\"${build.web.dir}/WEB-INF\" type=\"dir\" property=\"snapshot.valid\"/>\n"
                + "        <fail unless=\"snapshot.valid\" message=\"Built snapshot is missing WEB-INF.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"deploy-exploded\" description=\"Unsafe legacy direct deployment is blocked; use auto-ant reconcile.\">\n"
                + "        <fail message=\"Direct live deployment is disabled. Run auto-ant reconcile (or auto-ant reconcile --confirm-stopped).\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"deploy-war\" description=\"Unsafe direct WAR deployment is blocked.\">\n"
                + "        <fail message=\"Direct WAR deployment is disabled because it bypasses deployment coordination.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"branch-refresh\" description=\"Compatibility guard; use auto-ant reconcile.\">\n"
                + "        <fail message=\"Run auto-ant reconcile; direct Ant branch-refresh cannot coordinate the deployment transaction.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"sync-web\" description=\"Unsafe legacy incremental sync is blocked; use auto-ant reconcile.\">\n"
                + "        <fail message=\"Direct live sync is disabled because it cannot remove stale files safely. Run auto-ant reconcile.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"sync-web-inf\" description=\"Unsafe legacy incremental sync is blocked; use auto-ant reconcile.\">\n"
                + "        <fail message=\"Direct live sync is disabled. Run auto-ant reconcile.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"compile-hot\" description=\"Unsafe legacy hot compile is blocked; use auto-ant reconcile.\">\n"
                + "        <fail message=\"Direct live class replacement is disabled. Run auto-ant reconcile.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"write-context-descriptor\" depends=\"write-appbase-context-descriptor,write-docbase-context-descriptor\" description=\"Write Tomcat conf/Catalina/localhost context descriptor for the exploded app.\"/>\n"
                + "\n"
                + "    <target name=\"write-appbase-context-descriptor\" unless=\"context.descriptor.docBase\">\n"
                + "        <fail unless=\"deploy.dir\" message=\"Set deploy.dir in auto-ant.local.properties.\"/>\n"
                + "        <fail unless=\"context.descriptor.file.name\" message=\"Set context.descriptor.file.name in auto-ant.properties.\"/>\n"
                + "        <mkdir dir=\"${context.descriptor.dir}\"/>\n"
                + "        <echo file=\"${context.descriptor.file}\" message=\"&lt;Context reloadable=&quot;true&quot;/&gt;&#10;\"/>\n"
                + "        <echo message=\"Wrote Tomcat appBase context descriptor ${context.descriptor.file}; deploy.dir should be ${catalina.base}/webapps/${context.deploy.name}.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"write-docbase-context-descriptor\" if=\"context.descriptor.docBase\">\n"
                + "        <fail unless=\"context.descriptor.file.name\" message=\"Set context.descriptor.file.name in auto-ant.properties.\"/>\n"
                + "        <mkdir dir=\"${context.descriptor.dir}\"/>\n"
                + "        <echo file=\"${context.descriptor.file}\" message=\"&lt;Context docBase=&quot;${context.descriptor.docBase}&quot; reloadable=&quot;true&quot;/&gt;&#10;\"/>\n"
                + "        <echo message=\"Wrote Tomcat external docBase context descriptor ${context.descriptor.file}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"reload-hint\" description=\"Print Tomcat reload instructions.\">\n"
                + "        <echo message=\"Reload ${context.path} using auto-ant reload, Tomcat Manager, or restart Tomcat.\"/>\n"
                + "    </target>\n"
                + "</project>\n";
    }

    private String escape(String value) {
        return value.replace("&", "&amp;")
                .replace("\"", "&quot;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }
}
