package com.gei.autoant.generate;

import com.gei.autoant.model.ProjectModel;

import java.nio.file.Path;

public final class BuildXmlWriter {
    public String write(ProjectModel model) {
        StringBuilder sourcePath = new StringBuilder();
        for (Path sourceRoot : ModelValues.sourceRoots(model)) {
            sourcePath.append("        <pathelement location=\"")
                    .append(escape(ModelValues.relativePath(model, sourceRoot)))
                    .append("\"/>\n");
        }

        StringBuilder classpath = new StringBuilder();
        for (Path libraryRoot : ModelValues.libraryRoots(model)) {
            classpath.append("        <fileset dir=\"")
                    .append(escape(ModelValues.relativePath(model, libraryRoot)))
                    .append("\" erroronmissingdir=\"false\">\n")
                    .append("            <include name=\"**/*.jar\"/>\n")
                    .append("        </fileset>\n");
        }

        StringBuilder copyLibs = new StringBuilder();
        for (Path libraryRoot : ModelValues.libraryRoots(model)) {
            copyLibs.append("        <copy todir=\"${build.web.dir}/WEB-INF/lib\" failonerror=\"false\">\n")
                    .append("            <fileset dir=\"")
                    .append(escape(ModelValues.relativePath(model, libraryRoot)))
                    .append("\" erroronmissingdir=\"false\">\n")
                    .append("                <include name=\"**/*.jar\"/>\n")
                    .append("            </fileset>\n")
                    .append("        </copy>\n");
        }

        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<project name=\"" + escape(ModelValues.appName(model)) + "\" default=\"clean-build\" basedir=\".\">\n"
                + "    <description>Plain Ant build generated by auto-ant for a legacy Tomcat web app.</description>\n"
                + "\n"
                + "    <property file=\"auto-ant.local.properties\"/>\n"
                + "    <property file=\"auto-ant.properties\"/>\n"
                + "    <property name=\"deploy.dir\" location=\"${catalina.base}/webapps/${context.deploy.name}\"/>\n"
                + "    <property name=\"context.descriptor.dir\" location=\"${catalina.base}/conf/Catalina/localhost\"/>\n"
                + "    <property name=\"context.descriptor.file\" location=\"${context.descriptor.dir}/${context.descriptor.file.name}\"/>\n"
                + "\n"
                + "    <path id=\"source.path\">\n"
                + sourcePath
                + "    </path>\n"
                + "\n"
                + "    <path id=\"compile.classpath\">\n"
                + classpath
                + "        <!-- Provided by Tomcat at runtime; needed only to compile servlet/JSP API references. -->\n"
                + "        <fileset dir=\"${tomcat.home}/lib\" erroronmissingdir=\"false\">\n"
                + "            <include name=\"*.jar\"/>\n"
                + "        </fileset>\n"
                + "        <fileset dir=\"${catalina.base}/lib\" erroronmissingdir=\"false\">\n"
                + "            <include name=\"*.jar\"/>\n"
                + "        </fileset>\n"
                + "    </path>\n"
                + "\n"
                + "    <target name=\"clean\" description=\"Delete build and dist output.\">\n"
                + "        <delete dir=\"${build.dir}\"/>\n"
                + "        <delete dir=\"${dist.dir}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"init\" description=\"Create build directories.\">\n"
                + "        <mkdir dir=\"${classes.dir}\"/>\n"
                + "        <mkdir dir=\"${build.web.dir}/WEB-INF/lib\"/>\n"
                + "        <mkdir dir=\"${dist.dir}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"compile\" depends=\"init\" description=\"Compile Java source into WEB-INF/classes.\">\n"
                + "        <delete dir=\"${classes.dir}\"/>\n"
                + "        <mkdir dir=\"${classes.dir}\"/>\n"
                + "        <javac destdir=\"${classes.dir}\" includeantruntime=\"false\" debug=\"true\" release=\"${java.release}\">\n"
                + "            <src refid=\"source.path\"/>\n"
                + "            <classpath refid=\"compile.classpath\"/>\n"
                + "        </javac>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"copy-web\" depends=\"init\" description=\"Copy web root into the exploded build directory.\">\n"
                + "        <copy todir=\"${build.web.dir}\">\n"
                + "            <fileset dir=\"${web.dir}\" erroronmissingdir=\"false\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"copy-libs\" depends=\"init\" description=\"Copy project libraries into WEB-INF/lib.\">\n"
                + copyLibs
                + "    </target>\n"
                + "\n"
                + "    <target name=\"war\" depends=\"copy-web,compile,copy-libs\" description=\"Create dist WAR.\">\n"
                + "        <war destfile=\"${dist.dir}/${war.name}\" basedir=\"${build.web.dir}\" needxmlfile=\"false\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"clean-build\" depends=\"clean,war\" description=\"Clean and build WAR.\"/>\n"
                + "\n"
                + "    <target name=\"deploy-exploded\" depends=\"clean,copy-web,compile,copy-libs\" description=\"Clean, build, and copy exploded app to Tomcat webapps.\">\n"
                + "        <fail unless=\"deploy.dir\" message=\"Set deploy.dir in auto-ant.local.properties.\"/>\n"
                + "        <delete dir=\"${deploy.dir}\"/>\n"
                + "        <mkdir dir=\"${deploy.dir}\"/>\n"
                + "        <copy todir=\"${deploy.dir}\">\n"
                + "            <fileset dir=\"${build.web.dir}\"/>\n"
                + "        </copy>\n"
                + "        <antcall target=\"write-context-descriptor\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"deploy-war\" depends=\"war\" description=\"Copy WAR to Tomcat webapps.\">\n"
                + "        <fail unless=\"catalina.base\" message=\"Set catalina.base in auto-ant.local.properties.\"/>\n"
                + "        <copy file=\"${dist.dir}/${war.name}\" todir=\"${catalina.base}/webapps\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"sync-web\" description=\"Copy web/front-end files to deployed exploded app.\">\n"
                + "        <fail unless=\"deploy.dir\" message=\"Set deploy.dir in auto-ant.local.properties.\"/>\n"
                + "        <available file=\"${deploy.dir}\" type=\"dir\" property=\"deployed.webapp.exists\"/>\n"
                + "        <fail unless=\"deployed.webapp.exists\" message=\"Deployed exploded app not found at ${deploy.dir}. Set deploy.dir to the running exploded app folder or run ant deploy-exploded first.\"/>\n"
                + "        <echo message=\"Syncing frontend files from ${web.dir} to ${deploy.dir}\"/>\n"
                + "        <copy todir=\"${deploy.dir}\" preservelastmodified=\"true\">\n"
                + "            <fileset dir=\"${web.dir}\" erroronmissingdir=\"false\">\n"
                + "                <exclude name=\"WEB-INF/**\"/>\n"
                + "                <exclude name=\"META-INF/**\"/>\n"
                + "            </fileset>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"sync-web-inf\" description=\"Copy JSP/view/static resources to deployed exploded app without redeploying config or libraries.\">\n"
                + "        <fail unless=\"deploy.dir\" message=\"Set deploy.dir in auto-ant.local.properties.\"/>\n"
                + "        <available file=\"${deploy.dir}\" type=\"dir\" property=\"deployed.webapp.exists\"/>\n"
                + "        <fail unless=\"deployed.webapp.exists\" message=\"Deployed exploded app not found at ${deploy.dir}. Set deploy.dir to the running exploded app folder or run ant deploy-exploded first.\"/>\n"
                + "        <echo message=\"Syncing JSP/view/static resources from ${web.dir} to ${deploy.dir}\"/>\n"
                + "        <copy todir=\"${deploy.dir}\" preservelastmodified=\"true\">\n"
                + "            <fileset dir=\"${web.dir}\" erroronmissingdir=\"false\">\n"
                + "                <include name=\"**/*.jsp\"/>\n"
                + "                <include name=\"**/*.jspf\"/>\n"
                + "                <include name=\"**/*.tag\"/>\n"
                + "                <include name=\"**/*.tagx\"/>\n"
                + "                <include name=\"**/*.tld\"/>\n"
                + "                <include name=\"**/*.html\"/>\n"
                + "                <include name=\"**/*.htm\"/>\n"
                + "                <include name=\"**/*.css\"/>\n"
                + "                <include name=\"**/*.js\"/>\n"
                + "                <include name=\"**/*.ts\"/>\n"
                + "                <include name=\"**/*.png\"/>\n"
                + "                <include name=\"**/*.jpg\"/>\n"
                + "                <include name=\"**/*.jpeg\"/>\n"
                + "                <include name=\"**/*.gif\"/>\n"
                + "                <include name=\"**/*.svg\"/>\n"
                + "                <include name=\"**/*.webp\"/>\n"
                + "                <include name=\"**/*.ico\"/>\n"
                + "                <include name=\"**/*.woff\"/>\n"
                + "                <include name=\"**/*.woff2\"/>\n"
                + "                <exclude name=\"WEB-INF/classes/**\"/>\n"
                + "                <exclude name=\"WEB-INF/lib/**\"/>\n"
                + "                <exclude name=\"WEB-INF/web.xml\"/>\n"
                + "                <exclude name=\"META-INF/**\"/>\n"
                + "            </fileset>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"compile-hot\" depends=\"compile\" description=\"Compile Java and copy classes to deployed exploded app.\">\n"
                + "        <fail unless=\"deploy.dir\" message=\"Set deploy.dir in auto-ant.local.properties.\"/>\n"
                + "        <delete dir=\"${deploy.dir}/WEB-INF/classes\"/>\n"
                + "        <mkdir dir=\"${deploy.dir}/WEB-INF/classes\"/>\n"
                + "        <copy todir=\"${deploy.dir}/WEB-INF/classes\">\n"
                + "            <fileset dir=\"${classes.dir}\"/>\n"
                + "        </copy>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"write-context-descriptor\" depends=\"write-appbase-context-descriptor,write-docbase-context-descriptor\" description=\"Write Tomcat conf/Catalina/localhost context descriptor for the exploded app.\"/>\n"
                + "\n"
                + "    <target name=\"write-appbase-context-descriptor\" unless=\"context.descriptor.docBase\">\n"
                + "        <fail unless=\"deploy.dir\" message=\"Set deploy.dir in auto-ant.local.properties.\"/>\n"
                + "        <fail unless=\"context.descriptor.file.name\" message=\"Set context.descriptor.file.name in auto-ant.properties.\"/>\n"
                + "        <mkdir dir=\"${context.descriptor.dir}\"/>\n"
                + "        <echo file=\"${context.descriptor.file}\" message=\"&lt;Context reloadable=&quot;true&quot;/&gt;&#10;\"/>\n"
                + "        <echo message=\"Wrote Tomcat appBase context descriptor ${context.descriptor.file}; deploy.dir should be ${catalina.base}/webapps/${context.deploy.name}.\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"write-docbase-context-descriptor\" if=\"context.descriptor.docBase\">\n"
                + "        <fail unless=\"context.descriptor.file.name\" message=\"Set context.descriptor.file.name in auto-ant.properties.\"/>\n"
                + "        <mkdir dir=\"${context.descriptor.dir}\"/>\n"
                + "        <echo file=\"${context.descriptor.file}\" message=\"&lt;Context docBase=&quot;${context.descriptor.docBase}&quot; reloadable=&quot;true&quot;/&gt;&#10;\"/>\n"
                + "        <echo message=\"Wrote Tomcat external docBase context descriptor ${context.descriptor.file}\"/>\n"
                + "    </target>\n"
                + "\n"
                + "    <target name=\"reload-hint\" description=\"Print Tomcat reload instructions.\">\n"
                + "        <echo message=\"Reload ${context.path} using auto-ant reload, Tomcat Manager, or restart Tomcat.\"/>\n"
                + "    </target>\n"
                + "</project>\n";
    }

    private String escape(String value) {
        return value.replace("&", "&amp;")
                .replace("\"", "&quot;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }
}