package com.gei.autoant.generate;

import com.gei.autoant.model.ProjectModel;

public final class PropertiesWriter {
    public String writeShared(ProjectModel model) {
        String appName = ModelValues.appName(model);
        String webDir = ModelValues.relativePath(model, ModelValues.webRoot(model));
        String webInfDir = ModelValues.relativePath(model, ModelValues.webInf(model));
        String srcDirs = ModelValues.commaPaths(model, ModelValues.sourceRoots(model));
        String libDirs = ModelValues.commaPaths(model, ModelValues.libraryRoots(model));

        return "# auto-ant.properties\n"
                + "# Shared project settings generated by auto-ant.\n"
                + "\n"
                + "app.name=" + appName + "\n"
                + "context.path=" + ModelValues.contextPath(model) + "\n"
                + "java.release=" + ModelValues.javaRelease(model) + "\n"
                + "\n"
                + "src.dirs=" + srcDirs + "\n"
                + "web.dir=" + webDir + "\n"
                + "webinf.dir=" + webInfDir + "\n"
                + "lib.dirs=" + libDirs + "\n"
                + "\n"
                + "build.dir=build\n"
                + "build.web.dir=build/web\n"
                + "classes.dir=build/web/WEB-INF/classes\n"
                + "dist.dir=dist\n"
                + "war.name=" + appName + ".war\n"
                + "\n"
                + "reload.strategy=" + ModelValues.reloadStrategy(model) + "\n";
    }

    public String writeLocal(ProjectModel model) {
        String tomcatHome = ModelValues.tomcatHome(model);
        return "# auto-ant.local.properties\n"
                + "# Local machine settings. Do not commit this file.\n"
                + "\n"
                + "tomcat.home=" + tomcatHome + "\n"
                + "catalina.base=" + tomcatHome + "\n"
                + "\n"
                + "tomcat.manager.url=" + ModelValues.managerUrl(model) + "\n"
                + "tomcat.manager.user=\n"
                + "tomcat.manager.password=\n";
    }
}